{"name": "Проверка получения ошибки при повторном использовании логина для создания курьера", "status": "passed", "description": "Проверяются код и тело ответа.", "start": 1723375730191, "stop": 1723375730339, "uuid": "b4eaefa7-4a3b-4b61-851c-0362e703a0e6", "historyId": "6f67603245d03577c0bb7ad6998f5f65", "testCaseId": "6f67603245d03577c0bb7ad6998f5f65", "fullName": "tests.test_courier_create.TestCourierCreate#test_create_courier_account_login_taken_conflict", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "6908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create"}]}