{"name": "Проверка ошибки при попытке авторизации несуществующего пользователя", "status": "passed", "description": "Проверяется ошибка при попытке авторизации под несуществующим пользователем.", "start": 1723375732127, "stop": 1723375732251, "uuid": "387d5a9f-6e1b-425a-b5aa-d1c601ce9c0e", "historyId": "c828d7d31d8165c6562cbf1838764de1", "testCaseId": "c828d7d31d8165c6562cbf1838764de1", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_nonexistent_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "6908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}